### ISSUE TITLE
Nao consigo fazer o bot funcionar

### ISSUE THREAD

**Issue by buipk** [mpcabete/bombcrypto-bot#126]
Boa tarde,

Nao consigo fazer o bot funcionar de qualquer jeito. ja utilizei antes do update chapta sem problema mas agora com o novo update o bot nao funciona.

O rato nao mexe de todo e quando mexe (muito raro) apenas mexe para o canto superior da tela sem clicar em nada.

Ja tentei instalar e desinstalar o codigo. Usei diferentes browsers. Ja mudei a resoluçao do broswer. Ja mudei resoluçao do pc e o rato nao mexe de todo.

**Comment by cesarfran12** [comment]
verifica a resolução e o zoom do computador
abre cmd 
cd\bomb (se  tiveres a pasta do bomb no disco C:)
pip install -r requirements.txt

**Comment by buipk** [comment]
a resoluçao do broswer esta a 100% como recomendado e a resolucao do windows esta em 1920x1080.
Continuo sem conseguir fazer o bot funcionar

**Comment by Aspellian** [comment]
I have the same problem. I tried to install the bot on 4 different PCs. On the first it works well, on the second - it does not press the button to connect to Metamask (but otherwise it works), on the third - the cursor goes up and does nothing, on the fourth - the cursor presses some buttons, and then moves to another monitor. I did everything the same on all PCs. I don't see any pattern ...
__________________________________________________
Eu tenho o mesmo problema. Tentei instalar o bot em 4 PCs diferentes. Na primeira funciona bem, na segunda - não pressiona o botão para conectar ao Metamask (mas por outro lado funciona), na terceira - o cursor sobe e não faz nada, na quarta - o cursor pressiona alguns botões, e então passa para outro monitor. Fiz tudo igual em todos os PCs. Não vejo nenhum padrão ...

**Comment by Hermanyo** [comment]
Try to adjust threshold in config.yaml

**Comment by FergusonxD** [comment]
conseguiu resolver man?Também não consigo!

**Comment by Aspellian** [comment]
> conseguiu resolver man?Também não consigo!

No. It seems that the bot cannot correctly identify the "working window"
