### ISSUE TITLE
Rest in Home

### ISSUE THREAD

**Issue by ggskiawp** [mpcabete/bombcrypto-bot#137]
Hi.

Just a request to add a feature where in heroes can rest in the house that I purchased for them.
And if there's a way to choose how many minutes they will work and be put to rest.
If you can send me a direct message mr. mpcabete and work things out then I promise to give at least $125.00 of donation via BNB to your metamask wallet.

Thank you.

**Comment by Nucito** [comment]
> 

Hello, the option to choose how long he will work already exists in the project :) Creating an option to put them to sleep in the house would be easy, the only more annoying point to do would be choosing which characters would go to the house. With an OCR it would be possible to do...

**Comment by ggskiawp** [comment]
Hi.

What if putting whatever character on your inventory to the home?
If that is easy, can that be done?
What I'll just do is use that number of hero that my home is capable to cater.

**Comment by juniortopanotti** [comment]
@ggskiawp add me on discord, i can do this and other cool things for you Topanotti#9911, let me show to you.

**Comment by ggskiawp** [comment]
@juniortopanotti 

I just added you.
I'm bullishbear in discord.

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?
