### ISSUE TITLE
Sobre a atualização para logar via login e senha?

### ISSUE THREAD

**Issue by cleisonmsilva** [mpcabete/bombcrypto-bot#731]

**Comment by MaikonDosSantos** [comment]
opa. querendo tambem aqui.

**Comment by MaikonDosSantos** [comment]
que so entre automatico via wallet mesmo...

**Comment by jujubas6** [comment]
eae galera alguma solução para esse novo login do bomb para poder funcionar o bot mesmo se for disconectado?

**Comment by llFerreira** [comment]
Só inserir essa imagem na pasta "targets" com o nome "select-wallet-1-no-hover", que volta ao normal
 


![select-wallet-1-no-hover](https://user-images.githubusercontent.com/41524514/156014639-12587c47-05be-4dcf-8dce-8912b559cbb0.png)

**Comment by jujubas6** [comment]
vlw mano muito obrigado.

**Comment by felippetadeu** [comment]
Para multiaccount pode ser usado este: https://github.com/felippetadeu/bombcrypto-multibot
Tem integração tmb com o Telegram

**Comment by llFerreira** [comment]
> Para multiaccount pode ser usado este: https://github.com/felippetadeu/bombcrypto-multibot Tem integração tmb com o Telegram

Pra mim está dando erro de "Saldo nao encontrado", como corrigir?

**Comment by felippetadeu** [comment]
> > Para multiaccount pode ser usado este: https://github.com/felippetadeu/bombcrypto-multibot Tem integração tmb com o Telegram
> 
> Pra mim está dando erro de "Saldo nao encontrado", como corrigir?

Corrigido!

**Comment by Blue-Skyer** [comment]
Hello, We noticed that, instead of contributing the fix in the current repo (https://github.com/mpcabete/bombcrypto-bot), felippetadeu (https://github.com/felippetadeu) shared the repo (https://github.com/felippetadeu/bombcrypto-multibot), in which felippetadeu is one of the contributors. We would like to highlight this as a distasteful "self-promotion" (promoting the use of a project without mentioning that felippetadeu is associated with the project).
Regards, Blue Skyer.

**Comment by Blue-Skyer** [comment]
Hello, We noticed that, instead of contributing the fix in the current repo (https://github.com/mpcabete/bombcrypto-bot), felippetadeu (https://github.com/felippetadeu) shared the repo (https://github.com/felippetadeu/bombcrypto-multibot), in which felippetadeu is one of the contributors. We would like to highlight this as a distasteful "self-promotion" (promoting the use of a project without mentioning that felippetadeu is associated with the project).
Regards, Blue Skyer.
